### ISSUE TITLE
The mechanic to come up with top 10 jobs

### ISSUE THREAD

**Issue by jackyho112** [UBC-MDS/DSCI532_Group210_JobsAnalysis#14]
We are going with historical ratios for now. How does everyone feel? @bbaillie @merveshin

**Comment by bbaillie** [comment]
I have code for both, and can make the figures work for both, just need to know which one you prefer. @merveshin

**Comment by bbaillie** [comment]
Mechanic chosen was historical difference in proportion so that it is the same formula as used in the other figure
