### ISSUE TITLE
Reflection

### ISSUE THREAD

**Issue by jackyho112** [UBC-MDS/DSCI532_Group210_JobsAnalysis#23]
> In this section, you should (as a group) critique your dashboard and point out what it does well, what its limitations are, and what are good future improvements and additions. In this section, you should also clearly document how you addressed the feedback (GitHub issues) you received from your peers and the TAs. Point form is fine, but they need to be full sentences. This section should not be more than 500 words.

Let's reflect!!!!!!

**Comment by bbaillie** [comment]
I think the app would look better if we could centre the figures on the page
I also think it would look nicer if we were able to format the labels above the drop down menus to have some more space between them and be a bit bigger in font. 
The title of the page might look better with a bit of space added so its not right at the top of the page, and I think the blue background can make it a bit hard to read

**Comment by bbaillie** [comment]
It would also be nice if we could change the font of labels in the future so they aren't so block like
