### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by vigchandra** [UBC-MDS/DSCI532_Group210_JobsAnalysis#34]
- Intro : `jobs` to `job types`
- On the third graph, when we do 'male dominated' option, it is difficult to gain any information.
- By default, showing all the lines is very confusing for the user and didn't know that selecting the bar on the right.
- The data source could be put up in the bottom.
- The reservations on the data source kinda question the credibility of the analysis. It would be worthwhile to put it to the end than begin with that.
- The layout could be discussed further - plot 2 graphs on the top and the big one in the bottom?
- Wrap the header information in the 'Jumbo'.
- Gray background could be implemented instead of the blue if it was going to be any bigger.

**Comment by jackyho112** [comment]
https://github.com/UBC-MDS/DSCI532_Group210_JobsAnalysis/issues/36
