### ISSUE TITLE
Peer review feedback

### ISSUE THREAD

**Issue by mglu123** [UBC-MDS/DSCI532_Group210_JobsAnalysis#35]
Insightful research question!
1. Rotate X axis label (Year)

2 .Use interpolation or other method to handle missing data.

3. Add a subtitle or boundary between plots

4. Add a short description before each plot

5. Last plot: Most male dominate show re-sort the bar chart from low too high.

6. Resort balance bar chart based on distance from 50%.

7. Tooltip on the last bar.

**Comment by bbaillie** [comment]
- From descriptions at the top, if they are about a certain figure put it above that figure.
-  Also the usage description above the last figure should be placed above the figure and in the same font as the description data. 
- use a nicer dashboard layout, maybe the one Firas used for one of the apps in lecture
- add line tooltip to first plot
- Change the description of gender dominant group to specify if there are two men to every woman etc

**Comment by jackyho112** [comment]
https://github.com/UBC-MDS/DSCI532_Group210_JobsAnalysis/issues/36
